version: 2
jobs:
  build:
    docker:
      - image: poldrack/narps-analysis 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:d9:2a:de:d8:40:56:15:af:c7:34:93:ad:d2:85:d1"
      - checkout
      - run:
           name: static analysis and style check using flake8
           command: |
             pip install -U flake8
             flake8 ImageAnalyses
      - run:
          name: Get codecov
          command: python -m pip install codecov
      - run:
           name: run main narps tests
           command: |
             pip install -U pytest pytest-cov
             source /etc/fsl/5.0/fsl.sh; pytest --cov=./ImageAnalyses-q --cov-report=xml:/tmp/tests.xml ImageAnalyses/tests.py
      - run:
          name: Submit test coverage
          command: |
            python -m codecov --file /tmp/tests.xml \
                -e CIRCLE_JOB
      - run:
           name: run R script test
           command: |
             cat /root/project/ImageAnalyses/*.Rmd | grep library >| /root/project/ImageAnalyses/R_libraries.R
             export NARPS_BASEDIR="/tmp/data"; Rscript -e 'library(rmarkdown); rmarkdown::render("/root/project/ImageAnalyses/DecisionAnalysis.Rmd", "html_document", output_dir = "/tmp/data/figures")' 
             cd /tmp/data; tar zcvf results.tgz ./cached ./figures ./logs ./metadata ./image_diagnostics ./output/unthresh_concat_zstat/hypo*_voxelmap.nii.gz
      - store_artifacts:
          path: /tmp/data/results.tgz

