version: 2
jobs:
  build:
    docker:
      - image: poldrack/narps-analysis 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:d9:2a:de:d8:40:56:15:af:c7:34:93:ad:d2:85:d1"
      - checkout
      - run:
           name: run narps tests
           command: |
             pip install -U pytest
             cd analysis; pytest -q narps.py
