version: 2
jobs:
  build:
    docker:
      - image: poldrack/narps-analysis 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:d9:2a:de:d8:40:56:15:af:c7:34:93:ad:d2:85:d1"
      - checkout
      - run:
           name: run main narps tests
           command: |
             pip install -U pytest pytest-cov
             source /etc/fsl/5.0/fsl.sh; pytest --cov=./analysis -q analysis/tests.py
      - run:
           name: static analysis and style check using flake8
           command: |
             pip install -U flake8
             flake8 analysis
      - run:
           name: coverage
           command: |
              pip install coveralls
              coveralls

