version: 2
jobs:
  build:
    docker:
      - image: poldrack/narps-analysis 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:90:5e:75:b6:2c:3c:a3:46:51:4a:09:ac:d9:84:0f"
      - checkout
      - run:
           name: run narps tests
           command: |
             make test
