version: 2
jobs:
  build:
    docker:
      - image: poldrack/narps-analysis 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:d9:2a:de:d8:40:56:15:af:c7:34:93:ad:d2:85:d1"
      - checkout
      - run:
           name: run main narps tests
           command: |
             pip install -U pytest pytest-cov
             source /etc/fsl/5.0/fsl.sh; pytest --cov=./ImageAnalyses-q ImageAnalyses/tests.py
             cd /tmp/data; tar zcvf results.tgz ./cached ./figures ./logs
      - run:
           name: run R script test
           command: |
             export BASEDIR="/tmp/data"
             cat /root/project/ImageAnalyses/*.Rmd | grep library >| /root/project/ImageAnalyses/R_libraries.R
             Rscript -e 'library(rmarkdown); rmarkdown::render("/root/project/ImageAnalyses/DecisionAnalysis.Rmd", "html_document", output_dir = "/tmp/data/figures")' 
      - run:
           name: static analysis and style check using flake8
           command: |
             pip install -U flake8
             flake8 ImageAnalyses
      - run:
           name: coverage
           command: |
              pip install coveralls
              coveralls
      - store_artifacts:
          path: /tmp/data/results.tgz

